# Generated by Django 5.0.6 on 2024-10-06 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edugami_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='rut',
            field=models.CharField(default='23324432-1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='tests',
            field=models.ManyToManyField(to='edugami_app.test'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='StudentTestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('correct', models.FloatField()),
                ('wrong', models.FloatField()),
                ('skipped', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edugami_app.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edugami_app.test')),
            ],
            options={
                'unique_together': {('student', 'test')},
            },
        ),
    ]
